#!/bin/sh

CFG=${ZPROXY_CFG:-/etc/3proxy/3proxy.cfg}

# Ожидаем пока поднимется tun интерфейс
while [ ! -d /sys/class/net/tun0 ]; do
  sleep 1
done

sleep 5

if [ -f $CFG ]; then
  /opt/3proxy/bin/3proxy $CFG
else
  > $CFG

  if [  -n "$ZPROXY_NSERVERS" ]; then
    for s in $ZPROXY_NSERVERS; do
      echo "nserver $s" >> $CFG
    done
  fi

  [ -n "$ZPROXY_NSCACHE" ] && echo "nscache $ZPROXY_NSCACHE"  >> $CFG
  [ -n "$ZPROXY_LOG" ] && echo "log $ZPROXY_LOG" >> $CFG
  [ -n "$ZPROXY_LOGFORMAT" ] && echo "logformat $ZPROXY_LOGFORMAT" >> $CFG
  [ -n "$ZPROXY_LOGROTATE" ] && echo "rotate $ZPROXY_LOGROTATE" >> $CFG

  if [ -n "$ZPROXY_EXTERNAL" ]; then
    echo "external $ZPROXY_EXTERNAL" >> $CFG
  else
    echo "external 0.0.0.0" >> $CFG
  fi

  if [ -n "$ZPROXY_INTERNAL" ]; then
    echo "internal $ZPROXY_INTERNAL" >> $CFG
  else
    DEV=`ip -j ro get 255.255.255.255 | jq -r '.[].dev'`
    IP=`ip -j address show dev "$DEV" | jq -r '.[].addr_info[] | select(.family == "inet") | .local'`
    echo "internal $IP" >> $CFG
  fi

  [ -n "$ZPROXY_MAXCONN" ] && echo "maxconn $ZPROXY_MAXCONN"
  
  if [ -n "$ZPROXY_ALLOW" ]; then
    echo "$ZPROXY_ALLOW" | sed 's/,/\n/g' | sed 's/^/allow /' >> $CFG
  else
    echo "allow *" >> $CFG
  fi

  cat << EOF >> $CFG
dnspr
proxy -n -p${ZPROXY_HTTP_PORT:-1080}
socks -n -p${ZPROXY_SOCKS_PORT:-1081}
admin -n -p${ZPROXY_ADMIN_PORT:-8080}
EOF
fi

